Vagrant.configure("2") do |pythonbox|
  pythonbox.vm.box = "ubuntu/focal64"
  pythonbox.vm.hostname = "pythonbox"
  pythonbox.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
  pythonbox.vm.provision "ansible_local" do |ansible|
  	ansible.playbook = "ansible.yml"
  end
end